/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorGato;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Humberto
 */
public class VentanaGato extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGato
     */
    private controlador.ControladorGato controlador;
    private int turno;
    private ImageIcon[] arregloImagen;
    
    public VentanaGato() {
        this.turno = 0;
        this.controlador = new ControladorGato(this);
        this.arregloImagen = new ImageIcon[2];
        this.arregloImagen[0] = new ImageIcon("letraO.png");
        this.arregloImagen[1] = new ImageIcon("letraX.gif");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlGato = new javax.swing.JPanel();
        btnIzqArriba = new javax.swing.JButton();
        btnIzqCentro = new javax.swing.JButton();
        btnIzqAbajo = new javax.swing.JButton();
        btnCentroArriba = new javax.swing.JButton();
        btnCentroCentro = new javax.swing.JButton();
        btnCentroAbajo = new javax.swing.JButton();
        btnDerArriba = new javax.swing.JButton();
        btnDerCentro = new javax.swing.JButton();
        btnDerAbajo = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlGato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIzqArriba.setMaximumSize(new java.awt.Dimension(73, 71));
        btnIzqArriba.setMinimumSize(new java.awt.Dimension(73, 71));
        btnIzqArriba.setPreferredSize(new java.awt.Dimension(73, 71));
        btnIzqArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzqArribaActionPerformed(evt);
            }
        });

        btnIzqCentro.setMaximumSize(new java.awt.Dimension(73, 71));
        btnIzqCentro.setMinimumSize(new java.awt.Dimension(73, 71));
        btnIzqCentro.setPreferredSize(new java.awt.Dimension(73, 71));
        btnIzqCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzqCentroActionPerformed(evt);
            }
        });

        btnIzqAbajo.setMaximumSize(new java.awt.Dimension(73, 71));
        btnIzqAbajo.setMinimumSize(new java.awt.Dimension(73, 71));
        btnIzqAbajo.setPreferredSize(new java.awt.Dimension(73, 71));
        btnIzqAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzqAbajoActionPerformed(evt);
            }
        });

        btnCentroArriba.setMaximumSize(new java.awt.Dimension(73, 71));
        btnCentroArriba.setMinimumSize(new java.awt.Dimension(73, 71));
        btnCentroArriba.setPreferredSize(new java.awt.Dimension(73, 71));
        btnCentroArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroArribaActionPerformed(evt);
            }
        });

        btnCentroCentro.setMaximumSize(new java.awt.Dimension(73, 71));
        btnCentroCentro.setMinimumSize(new java.awt.Dimension(73, 71));
        btnCentroCentro.setPreferredSize(new java.awt.Dimension(73, 71));
        btnCentroCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroCentroActionPerformed(evt);
            }
        });

        btnCentroAbajo.setMaximumSize(new java.awt.Dimension(73, 71));
        btnCentroAbajo.setMinimumSize(new java.awt.Dimension(73, 71));
        btnCentroAbajo.setPreferredSize(new java.awt.Dimension(73, 71));
        btnCentroAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroAbajoActionPerformed(evt);
            }
        });

        btnDerArriba.setMaximumSize(new java.awt.Dimension(73, 71));
        btnDerArriba.setMinimumSize(new java.awt.Dimension(73, 71));
        btnDerArriba.setPreferredSize(new java.awt.Dimension(73, 71));
        btnDerArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerArribaActionPerformed(evt);
            }
        });

        btnDerCentro.setMaximumSize(new java.awt.Dimension(73, 71));
        btnDerCentro.setMinimumSize(new java.awt.Dimension(73, 71));
        btnDerCentro.setPreferredSize(new java.awt.Dimension(73, 71));
        btnDerCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerCentroActionPerformed(evt);
            }
        });

        btnDerAbajo.setMaximumSize(new java.awt.Dimension(73, 71));
        btnDerAbajo.setMinimumSize(new java.awt.Dimension(73, 71));
        btnDerAbajo.setPreferredSize(new java.awt.Dimension(73, 71));
        btnDerAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerAbajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGatoLayout = new javax.swing.GroupLayout(pnlGato);
        pnlGato.setLayout(pnlGatoLayout);
        pnlGatoLayout.setHorizontalGroup(
            pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGatoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIzqAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzqCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzqArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCentroCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCentroArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCentroAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDerAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDerArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDerCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        pnlGatoLayout.setVerticalGroup(
            pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGatoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGatoLayout.createSequentialGroup()
                        .addComponent(btnCentroArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnCentroCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCentroAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlGatoLayout.createSequentialGroup()
                            .addComponent(btnDerArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDerCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDerAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGatoLayout.createSequentialGroup()
                            .addComponent(btnIzqArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnIzqCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnIzqAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTurno.setText("Turno:");

        lblJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public ControladorGato getControlador() {
        return controlador;
    }

    public void setControlador(ControladorGato controlador) {
        this.controlador = controlador;
    }
    
    public void cambiarTurno(boolean respuesta){
        //int turno;
        if (this.turno == 0){
            this.turno = 1;
        }
        else {
            this.turno = 0;
        }
    }
    
    public void mostrarMensajeGanador(){
        int resultado, respuesta;
        resultado = getControlador().establecerGanador();
        if (resultado == 0){
            respuesta = JOptionPane.showConfirmDialog(null,  "¿Jugar de Nuevo?", "Ganó Jugador "
                    + this.turno+1,
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION){
                resetearJuego();
            }
            else{
                this.dispose();
            }
            
        }
        else if (resultado == 1){
            respuesta = JOptionPane.showConfirmDialog (null,  "¿Jugar de Nuevo?", "Empate",
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION){
                resetearJuego();
            }
            else{
                this.dispose();
            }
        }
        
    }
    
    public void generarRespuesta (int pRespuesta){
        if (pRespuesta == JOptionPane.YES_OPTION){
            
        }
    }
    
    public void resetearJuego(){
        btnCentroAbajo.setEnabled(true);
        btnCentroArriba.setEnabled(true);
        btnCentroCentro.setEnabled(true);
        btnIzqAbajo.setEnabled(true);
        btnIzqArriba.setEnabled(true);
        btnIzqCentro.setEnabled(true);
        btnDerAbajo.setEnabled(true);
        btnDerArriba.setEnabled(true);
        btnDerCentro.setEnabled(true);
        btnCentroAbajo.setIcon(null);
        btnCentroArriba.setIcon(null);
        btnCentroCentro.setIcon(null);
        btnIzqAbajo.setIcon(null);
        btnIzqArriba.setIcon(null);
        btnIzqCentro.setIcon(null);
        btnDerAbajo.setIcon(null);
        btnDerArriba.setIcon(null);
        btnDerCentro.setIcon(null);
        getControlador().resetearJuego();
        this.turno = 0;
    }

    private void btnIzqArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzqArribaActionPerformed
        getControlador().recibirPosicion(0, 0);
        cambiarTurno(getControlador().getRespuesta());
        btnIzqArriba.setIcon(this.arregloImagen[this.turno]);
        btnIzqArriba.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnIzqArribaActionPerformed

    private void btnIzqCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzqCentroActionPerformed
        getControlador().recibirPosicion(0, 1);
        cambiarTurno(getControlador().getRespuesta());
        btnIzqCentro.setIcon(this.arregloImagen[this.turno]);
        btnIzqCentro.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnIzqCentroActionPerformed

    private void btnIzqAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzqAbajoActionPerformed
        getControlador().recibirPosicion(0, 2);
        cambiarTurno(getControlador().getRespuesta());
        btnIzqAbajo.setIcon(this.arregloImagen[this.turno]);
        btnIzqAbajo.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnIzqAbajoActionPerformed

    private void btnCentroArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroArribaActionPerformed
        getControlador().recibirPosicion(1, 0);
        cambiarTurno(getControlador().getRespuesta());
        btnCentroArriba.setIcon(this.arregloImagen[this.turno]);
        btnCentroArriba.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnCentroArribaActionPerformed

    private void btnCentroCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroCentroActionPerformed
        getControlador().recibirPosicion(1, 1);
        cambiarTurno(getControlador().getRespuesta());
        btnCentroCentro.setIcon(this.arregloImagen[this.turno]);
        btnCentroCentro.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnCentroCentroActionPerformed

    private void btnCentroAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroAbajoActionPerformed
        getControlador().recibirPosicion(1, 2);
        cambiarTurno(getControlador().getRespuesta());
        btnCentroAbajo.setIcon(this.arregloImagen[this.turno]);
        btnCentroAbajo.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnCentroAbajoActionPerformed

    private void btnDerArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerArribaActionPerformed
        getControlador().recibirPosicion(2, 0);
        cambiarTurno(getControlador().getRespuesta());
        btnDerArriba.setIcon(this.arregloImagen[this.turno]);
        btnDerArriba.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnDerArribaActionPerformed

    private void btnDerCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerCentroActionPerformed
        getControlador().recibirPosicion(2, 1);
        cambiarTurno(getControlador().getRespuesta());
        btnDerCentro.setIcon(this.arregloImagen[this.turno]);
        btnDerCentro.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnDerCentroActionPerformed

    private void btnDerAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerAbajoActionPerformed
        getControlador().recibirPosicion(2, 2);
        cambiarTurno(getControlador().getRespuesta());
        btnDerAbajo.setIcon(this.arregloImagen[this.turno]);
        btnDerAbajo.setEnabled(false);
        getControlador().cambiarTurno();
        mostrarMensajeGanador();
    }//GEN-LAST:event_btnDerAbajoActionPerformed
    
    
    public void setTurnoJugador(String pJugador){
        lblJugador.setText(pJugador);
    }
    
    public void desplegarError(String pMensajeError){
        JOptionPane.showMessageDialog(this, pMensajeError);
    }
    
    public void iniciarVentana(){
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(Exception e){
            System.out.println("UIManager Exception : "+e);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentroAbajo;
    private javax.swing.JButton btnCentroArriba;
    private javax.swing.JButton btnCentroCentro;
    private javax.swing.JButton btnDerAbajo;
    private javax.swing.JButton btnDerArriba;
    private javax.swing.JButton btnDerCentro;
    private javax.swing.JButton btnIzqAbajo;
    private javax.swing.JButton btnIzqArriba;
    private javax.swing.JButton btnIzqCentro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel pnlGato;
    // End of variables declaration//GEN-END:variables
}
